version: 2.1

job_defaults: &job_defaults
  parameters:
    postgres_image:
      type: string

    publish_coverage:
      type: boolean
      default: false

  environment:
    DATABASE_URL: postgresql://postgres@localhost/icms
    ICMS_DEBUG: 'True'
    DJANGO_SECRET_KEY: test
    DJANGO_SETTINGS_MODULE: config.settings.test

  working_directory: ~/code

  docker:
    - image: circleci/python:3.7-jessie-node-browsers

    - image: <<parameters.postgres_image>>
      environment:
        POSTGRES_DB=icms

  steps:
    - checkout

#    - restore_cache:
#        name: Restore pip cache
#        keys:
#          - v1-icms-{{ checksum "Pipfile.lock" }}
#          - v1-icms-

    - run:
        name: Install dependencies
        command: pip install pipenv && pipenv install --dev --deploy

#    - save_cache:
#        name: Save pip cache
#        key: v1-icms-{{ checksum "Pipfile.lock" }}
#        paths:
#          - /app
#          - /usr/local/bin
#          - /usr/local/lib/python3.6/site-packages

    - run:
        name: Install node modules
        command: npm install --production

    - run:
        name: Webpack build
        command: npm run deploy

    - run:
        name: Run tests
        command: pipenv run python -m pytest -p no:sugar --cov=web --cov=config web/tests

    - run:
        name: Run Flake8
        command: pipenv run python -m flake8

    - store_test_results:
        path: test-reports

    - when:
        condition: <<parameters.publish_coverage>>
        steps:
        - run:
            name: Publish coverage
            command: |
              wget -O codecov.sh https://codecov.io/bash
              bash ./codecov.sh -t ${COV_TOKEN}

jobs:
  build:
    <<: *job_defaults

workflows:
  version: 2

  # Current standard environment
  Default build:
    jobs:
      - build:
          publish_coverage: true
          postgres_image: postgres:9.5
